name: Build Translation Files
on: 
  push:
    paths:
      - 'src/argus/locales/**'
  pull_request:
    paths:
      - 'src/argus/locales/**'
  workflow_dispatch:
jobs:
  rebuild_translation_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v6

      - name: Install Gettext
        run: sudo apt-get install -y gettext
      
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      
      - name: Make File Executable
        run: chmod +x ./src/argus/locales/update_files.sh
        
      - name: Rebuild translation Files
        run: ./src/argus/locales/update_files.sh
      
      - uses: EndBug/add-and-commit@v10
        with:
          default_author: github_actions
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: 'rebuild translation files'
          push: true
          add: '*.mo' 